# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Okgit < Formula
  desc ""
  homepage "https://github.com/rajnandan1/okgit"
  version "1.0.17"

  on_macos do
    url "https://github.com/rajnandan1/okgit/releases/download/v1.0.17/okgit_1.0.17_darwin_all.tar.gz"
    sha256 "f296b533fef629a4f9bab9b4c18d644b868b21e5a127cba71fe753c2ad14aa6a"

    def install
      bin.install "okgit"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rajnandan1/okgit/releases/download/v1.0.17/okgit_1.0.17_linux_amd64.tar.gz"
        sha256 "000df3a0654c97a77320750eab7430a98f5483b80636868c10f9365eaccde02a"

        def install
          bin.install "okgit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rajnandan1/okgit/releases/download/v1.0.17/okgit_1.0.17_linux_arm64.tar.gz"
        sha256 "1eade472332dc814ea869970ab98b1bbd85d11e2e8958a98d5fb3038e9673273"

        def install
          bin.install "okgit"
        end
      end
    end
  end
end
